### ISSUE TITLE
[HDHomeRun Integration] "Device not found" error despite successful manual connection

### ISSUE THREAD

**Issue by cloudbr34k84** [uvjim/hass_hdhomerun#104]
Issue Description
I am encountering an issue with the custom integration for HDHomeRun. The integration logs the following error:
```
Logger: custom_components.hdhomerun
Source: custom_components/hdhomerun/__init__.py:105
integration: HDHomeRun (documentation, issues)
First occurred: 12:27:24 pm (611 occurrences)
Last logged: 7:27:13 pm

_async_data_coordinator_update (12605685) --> Device not found (fe80::218:ddff:fe26:568)
```

Despite this error, I am able to connect to the device manually, so the device seems to be functioning correctly outside of the integration.
![image](https://github.com/user-attachments/assets/6d80e7f7-8fe5-475b-9ac0-4f1b661af607)

**Steps to Reproduce**
Set up the HDHomeRun custom integration.
Observe the error in the logs.
Expected Behavior
The integration should successfully connect to the HDHomeRun device without logging errors.

**Actual Behavior**
The integration logs repeated instances of the "Device not found" error, but I can still connect to the device manually.

**Comment by uvjim** [comment]
This might be related: https://github.com/uvjim/hass_hdhomerun/issues/78
I'll make an assumption that you allowed the integration to be discovered automatically and added from there.  If you try removing the integration and manually specifying the IP, or allowing it to be discovered using UDP rather than SSDP, does that help?

If that doesn't work then could you provide the versions of HASS and the integration that you are using please?

**Comment by cloudbr34k84** [comment]
yeah i have done both, the discovery and adding it via IP address and im still seeing the same error message in my log

im using 2014.10 Core
2024.5.1 HDHome run

**Comment by uvjim** [comment]
Apologies for the delay coming back to you. I'm not seeing this happen at all so can't recreate it.

Could you remove the integration, ensure logging is turned on and try to add again please? Keep logging on for the integration until the error happens again.

If you send the logs over, I'll see if I can find where things are going wrong.

**Comment by jlipsit** [comment]
I am seeing the same problem. Running the latest version of HA:  

Core
2024.11.2
Supervisor
2024.11.3
Operating System
13.2
Frontend
20241106.2

![image](https://github.com/user-attachments/assets/9e63cae9-c83b-4a38-af67-15829bbb78a6)

**Comment by uvjim** [comment]
It appears that yours is also looking for the IPv6 address. Could you enable debug logging please and provide a full log after a restart of Home Assistant - I'm specifically looking to see what happens when an SSDP message comes in (I'm making an assumption that is the problem).

**Comment by jlipsit** [comment]
Just to be clear should I wait for the problem to occur- then turn on logging and restart and capture logs??  (We may miss what caused the issue?) or is it good enough to see how it tries to reconnect?

**Comment by uvjim** [comment]
Could you remove the integration, ensure logging is turned on and try to add again please? Keep logging on for the integration until the error happens again.

**Comment by jlipsit** [comment]
I captured the error and filter the log for you. Hopefully you can identify the issue. Let me know if you need anything else.  See attached log below. 

![HD Debug](https://github.com/user-attachments/assets/d3916ee1-9393-4685-8c14-a911b84f5813)
[HD Home Run Log Failure.txt](https://github.com/user-attachments/files/17948874/HD.Home.Run.Log.Failure.txt)

**Comment by uvjim** [comment]
Thank you. Would you be able to send over the diagnostics as well please? You can get those from clicking download diagnostics on the device. Thanks.

**Comment by jlipsit** [comment]
Here it is.  Thanks for working on this!

[config_entry-hdhomerun-01JDN312JMJA4198E4JDBF6XMC.json](https://github.com/user-attachments/files/17949189/config_entry-hdhomerun-01JDN312JMJA4198E4JDBF6XMC.json)

**Comment by uvjim** [comment]
I can see the code path it's following.  However, if like the OP said you're adding the device by either UDP scan or by specifying the IP address, i.e. by clicking the `Add Integration` button, then it shouldn't be getting followed.

I need to do some more checking because, I'm hoping the that IPv6 and IPv4 SSDP announcements use a different unique ID.  If they do, then I can key off that.  Although tracking the SSDP announcements down is easier said than done - I don't see them very often in my network for some reason.

**Comment by uvjim** [comment]
I've just pushed `2024.11.1b2`, could you try that please and see if it solves the issue?

**Comment by uvjim** [comment]
P.S.  You'll need to delete the integration you currently have setup and set it up again.  It should 🤞 be OK after that.

**Comment by uvjim** [comment]
Nope.  I'm pretty sure you should be OK once this is in place.  If it does happen again, then I'll probably need debugging at that point.  To be honest, the config flow probably needs tidying up a fair amount.  Let's give it a few days and see if the issue crops up again.

**Comment by jlipsit** [comment]
I really appreciate the work you did on this. It would be great to work in some control capabilities if you have some free time. I could donate $ to help. See the below "code examples" that I had ChatGPT put together. It would be great to have a media player control in HA for the HD Homerun tuners, ability to pull in the channel list and change channels and even display a stream.

[Request.txt](https://github.com/user-attachments/files/17951004/Request.txt)

**Comment by uvjim** [comment]
That's unlikely to happen based on this from 2022.

https://github.com/home-assistant/core/issues/67618

Essentially the browser can't handle the stream type so we can't use the built-in player for Home Assistant.

There's also only a couple of models of HDHomeRun that allow transcoding, so it'd be a lot of effort for only a small proportion of people (and I don't own one of those models).

The channel list is already pulled in, but there's not really anywhere to put it, that makes sense, considering that we can't take any action on it.

**Comment by jlipsit** [comment]
Please... Remote control alone would be great (since most people are viewing it on a TV) to be able to change and select channels automatically. Could you just pull in all the active channels from the users device and assign it to a Device (Button) for each tuner -  that when pressed would tune the tuner to that channel?  :-)

Check it out:
[Request 2.txt](https://github.com/user-attachments/files/17951311/Request.2.txt)

Example: 
![Button Example](https://github.com/user-attachments/assets/ae112d0b-4481-4fe1-a943-56f2c44f60b2)

![image](https://github.com/user-attachments/assets/f9e9cf4a-ad43-4517-b33d-c82aebe186f0)

**Comment by uvjim** [comment]
This should probably go into a different thread.

It's highly unlikely I'll do anything like that. I'm not sure it works the way you think it does.

Using HTTP you're instructing the client to go and retrieve the stream: https://info.hdhomerun.com/info/http_api. As we've already seen the browser can't load the stream so pretty pointless.

The UI proposed isn't feasible either. I have over 100 channels in my list. Having 100 buttons is a UX nightmare. This could be better achieved with a `select` entity, but you still have the issue of the browser not being able to play the stream.

You'd want to leave the URL set to auto because specifying a tuner wouldn't be a good idea - the tuner may well be locked by another process.

There is a document showing that `hdhomerun_config` can stream to a target device, but there are other integrations that have attempted to use that with varying success (it's not native in HAOS). I don't intend to include that into the `pyhdhr` implementation (which should in theory be a library, but I don't fancy maintaining it for anything other than the purposes of this integration - which incidentally I only created to get alerts about firmware updates).

**Comment by uvjim** [comment]
@cloudbr34k84 - have you had a chance to try the latest beta release to see if that helps?

**Comment by jlipsit** [comment]
Yes - no crashes since I started using it. I installed it just about 30 min after you put it up there.
